#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActivityBrowserModeSetListEntry

#include "Basic.hpp"

#include "ActivityBrowserModeSetListEntry_classes.hpp"
#include "ActivityBrowserModeSetListEntry_parameters.hpp"


namespace SDK
{

// Function ActivityBrowserModeSetListEntry.ActivityBrowserModeSetListEntry_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UActivityBrowserModeSetListEntry_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserModeSetListEntry.ActivityBrowserModeSetListEntry_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserModeSetListEntry_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnItemSelectionChanged");

	Params::ActivityBrowserModeSetListEntry_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserModeSetListEntry.ActivityBrowserModeSetListEntry_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UActivityBrowserModeSetListEntry_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserModeSetListEntry.ActivityBrowserModeSetListEntry_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UActivityBrowserModeSetListEntry_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserModeSetListEntry.ActivityBrowserModeSetListEntry_C.ExecuteUbergraph_ActivityBrowserModeSetListEntry
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserModeSetListEntry_C::ExecuteUbergraph_ActivityBrowserModeSetListEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_ActivityBrowserModeSetListEntry");

	Params::ActivityBrowserModeSetListEntry_C_ExecuteUbergraph_ActivityBrowserModeSetListEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserModeSetListEntry.ActivityBrowserModeSetListEntry_C.OnActivityNameSet
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             ActivityName                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UActivityBrowserModeSetListEntry_C::OnActivityNameSet(const class FText& ActivityName)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnActivityNameSet");

	Params::ActivityBrowserModeSetListEntry_C_OnActivityNameSet Parms{};

	Parms.ActivityName = std::move(ActivityName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserModeSetListEntry.ActivityBrowserModeSetListEntry_C.OnPreviewImageChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsLoading                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture*                         Texture                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserModeSetListEntry_C::OnPreviewImageChanged(const bool bIsLoading, const class UTexture* Texture)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPreviewImageChanged");

	Params::ActivityBrowserModeSetListEntry_C_OnPreviewImageChanged Parms{};

	Parms.bIsLoading = bIsLoading;
	Parms.Texture = Texture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserModeSetListEntry.ActivityBrowserModeSetListEntry_C.RefreshDisabledState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UActivityBrowserModeSetListEntry_C::RefreshDisabledState()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("RefreshDisabledState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserModeSetListEntry.ActivityBrowserModeSetListEntry_C.ResetSetDisabledColorationAnimation
// (Public, BlueprintCallable, BlueprintEvent)

void UActivityBrowserModeSetListEntry_C::ResetSetDisabledColorationAnimation()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ResetSetDisabledColorationAnimation");

	UObject::ProcessEvent(Func, nullptr);
}

}

