#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Assault_Armadillo

#include "Basic.hpp"

#include "B_Assault_Armadillo_classes.hpp"
#include "B_Assault_Armadillo_parameters.hpp"


namespace SDK
{

// Function B_Assault_Armadillo.B_Assault_Armadillo_C.ExecuteUbergraph_B_Assault_Armadillo
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_Armadillo_C::ExecuteUbergraph_B_Assault_Armadillo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_B_Assault_Armadillo");

	Params::B_Assault_Armadillo_C_ExecuteUbergraph_B_Assault_Armadillo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.HandleWeaponFiltering
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Assault_Armadillo_C::HandleWeaponFiltering()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleWeaponFiltering");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.OnLocalFailedToFireWhenOverheated
// (Event, Protected, BlueprintEvent)

void AB_Assault_Armadillo_C::OnLocalFailedToFireWhenOverheated()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnLocalFailedToFireWhenOverheated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.OnOverheatingValue
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   CurrentValue                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   MaxValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortWeaponOverheatState                State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInCooldown                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_Armadillo_C::OnOverheatingValue(float CurrentValue, float MaxValue, EFortWeaponOverheatState State, bool bIsInCooldown)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnOverheatingValue");

	Params::B_Assault_Armadillo_C_OnOverheatingValue Parms{};

	Parms.CurrentValue = CurrentValue;
	Parms.MaxValue = MaxValue;
	Parms.State = State;
	Parms.bIsInCooldown = bIsInCooldown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.OnPlayImpactFX
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// struct FHitResult                       HitResult                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// EPhysicalSurface                        ImpactPhysicalSurface                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFXSystemComponent*               SpawnedPSC                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_Armadillo_C::OnPlayImpactFX(const struct FHitResult& HitResult, EPhysicalSurface ImpactPhysicalSurface, class UFXSystemComponent* SpawnedPSC)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayImpactFX");

	Params::B_Assault_Armadillo_C_OnPlayImpactFX Parms{};

	Parms.HitResult = std::move(HitResult);
	Parms.ImpactPhysicalSurface = ImpactPhysicalSurface;
	Parms.SpawnedPSC = SpawnedPSC;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.OnPlayWeaponFireFX
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bPersistentFire                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bSecondaryFire                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_Armadillo_C::OnPlayWeaponFireFX(bool bPersistentFire, bool bSecondaryFire)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayWeaponFireFX");

	Params::B_Assault_Armadillo_C_OnPlayWeaponFireFX Parms{};

	Parms.bPersistentFire = bPersistentFire;
	Parms.bSecondaryFire = bSecondaryFire;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.OnRep_bStartLoop
// (BlueprintCallable, BlueprintEvent)

void AB_Assault_Armadillo_C::OnRep_bStartLoop()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnRep_bStartLoop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.OnStartOverheated
// (Event, Protected, BlueprintEvent)

void AB_Assault_Armadillo_C::OnStartOverheated()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnStartOverheated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.OnStopWeaponFireFX
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)

void AB_Assault_Armadillo_C::OnStopWeaponFireFX()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnStopWeaponFireFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.OnWeaponAttached
// (Event, Public, BlueprintEvent)

void AB_Assault_Armadillo_C::OnWeaponAttached()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnWeaponAttached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.OnWeaponDetached
// (Event, Public, BlueprintEvent)

void AB_Assault_Armadillo_C::OnWeaponDetached()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnWeaponDetached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.PlayFireAudio
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AB_Assault_Armadillo_C::PlayFireAudio()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PlayFireAudio");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.PressTrigger
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortWeapon*                      Weapon                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_Armadillo_C::PressTrigger(class AFortWeapon* Weapon)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PressTrigger");

	Params::B_Assault_Armadillo_C_PressTrigger Parms{};

	Parms.Weapon = Weapon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.PressTriggerServer
// (Net, NetServer, BlueprintCallable, BlueprintEvent)

void AB_Assault_Armadillo_C::PressTriggerServer()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PressTriggerServer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_Assault_Armadillo_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_Armadillo_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveEndPlay");

	Params::B_Assault_Armadillo_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.ReleaseTrigger
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortWeapon*                      Weapon                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_Armadillo_C::ReleaseTrigger(class AFortWeapon* Weapon)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReleaseTrigger");

	Params::B_Assault_Armadillo_C_ReleaseTrigger Parms{};

	Parms.Weapon = Weapon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.ReleaseTriggerServer
// (Net, NetServer, BlueprintCallable, BlueprintEvent)

void AB_Assault_Armadillo_C::ReleaseTriggerServer()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReleaseTriggerServer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.ReturnAudioParamToNormal
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Assault_Armadillo_C::ReturnAudioParamToNormal()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReturnAudioParamToNormal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.ShowOverheatDebug
// (BlueprintCallable, BlueprintEvent)

void AB_Assault_Armadillo_C::ShowOverheatDebug()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ShowOverheatDebug");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Assault_Armadillo.B_Assault_Armadillo_C.StopFireAudio
// (Public, BlueprintCallable, BlueprintEvent)

void AB_Assault_Armadillo_C::StopFireAudio()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("StopFireAudio");

	UObject::ProcessEvent(Func, nullptr);
}

}

