#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_MED_Treasure_Hunter_Fashion_AnimBp

#include "Basic.hpp"

#include "F_MED_Treasure_Hunter_Fashion_AnimBp_classes.hpp"
#include "F_MED_Treasure_Hunter_Fashion_AnimBp_parameters.hpp"


namespace SDK
{

// Function F_MED_Treasure_Hunter_Fashion_AnimBp.F_MED_Treasure_Hunter_Fashion_AnimBp_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UF_MED_Treasure_Hunter_Fashion_AnimBp_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("AnimGraph");

	Params::F_MED_Treasure_Hunter_Fashion_AnimBp_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function F_MED_Treasure_Hunter_Fashion_AnimBp.F_MED_Treasure_Hunter_Fashion_AnimBp_C.ExecuteUbergraph_F_MED_Treasure_Hunter_Fashion_AnimBp
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UF_MED_Treasure_Hunter_Fashion_AnimBp_C::ExecuteUbergraph_F_MED_Treasure_Hunter_Fashion_AnimBp(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_F_MED_Treasure_Hunter_Fashion_AnimBp");

	Params::F_MED_Treasure_Hunter_Fashion_AnimBp_C_ExecuteUbergraph_F_MED_Treasure_Hunter_Fashion_AnimBp Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function F_MED_Treasure_Hunter_Fashion_AnimBp.F_MED_Treasure_Hunter_Fashion_AnimBp_C.OnBeginCrouching
// (Event, Public, BlueprintEvent)

void UF_MED_Treasure_Hunter_Fashion_AnimBp_C::OnBeginCrouching()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnBeginCrouching");

	UObject::ProcessEvent(Func, nullptr);
}


// Function F_MED_Treasure_Hunter_Fashion_AnimBp.F_MED_Treasure_Hunter_Fashion_AnimBp_C.OnEndCrouching
// (Event, Public, BlueprintEvent)

void UF_MED_Treasure_Hunter_Fashion_AnimBp_C::OnEndCrouching()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnEndCrouching");

	UObject::ProcessEvent(Func, nullptr);
}

}

