#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: M_MED_Mystic_AnimBP

#include "Basic.hpp"

#include "M_MED_Mystic_AnimBP_classes.hpp"
#include "M_MED_Mystic_AnimBP_parameters.hpp"


namespace SDK
{

// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UM_MED_Mystic_AnimBP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("AnimGraph");

	Params::M_MED_Mystic_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UM_MED_Mystic_AnimBP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BlueprintUpdateAnimation");

	Params::M_MED_Mystic_AnimBP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_Constraint_181CE0E740E2F9FA591F88860907BAD5
// (BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_Constraint_181CE0E740E2F9FA591F88860907BAD5()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_Constraint_181CE0E740E2F9FA591F88860907BAD5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_Constraint_BDC00F33444A115B118A1CA2E2C154AB
// (BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_Constraint_BDC00F33444A115B118A1CA2E2C154AB()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_Constraint_BDC00F33444A115B118A1CA2E2C154AB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_Constraint_E12567584CF869837A1EEABD1739AA99
// (BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_Constraint_E12567584CF869837A1EEABD1739AA99()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_Constraint_E12567584CF869837A1EEABD1739AA99");

	UObject::ProcessEvent(Func, nullptr);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_01D3D2AA4976569701C52A89ED38C379
// (BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_01D3D2AA4976569701C52A89ED38C379()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_01D3D2AA4976569701C52A89ED38C379");

	UObject::ProcessEvent(Func, nullptr);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_3CFBC6654D29FF2B5CC6BD883CF0D503
// (BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_3CFBC6654D29FF2B5CC6BD883CF0D503()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_3CFBC6654D29FF2B5CC6BD883CF0D503");

	UObject::ProcessEvent(Func, nullptr);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_6E7CCFEA45DA2B4B2A15ED956300A971
// (BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_6E7CCFEA45DA2B4B2A15ED956300A971()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_6E7CCFEA45DA2B4B2A15ED956300A971");

	UObject::ProcessEvent(Func, nullptr);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_75D122DC4264B4CC796282B2DF3E354F
// (BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_75D122DC4264B4CC796282B2DF3E354F()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_75D122DC4264B4CC796282B2DF3E354F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_838E06EC49172460A8310A92ABC36F30
// (BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_838E06EC49172460A8310A92ABC36F30()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_838E06EC49172460A8310A92ABC36F30");

	UObject::ProcessEvent(Func, nullptr);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_98FB435F4245366F2B7F0A8A3E6A0204
// (BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_98FB435F4245366F2B7F0A8A3E6A0204()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EvaluateGraphExposedInputs_ExecuteUbergraph_M_MED_Mystic_AnimBP_AnimGraphNode_ModifyBone_98FB435F4245366F2B7F0A8A3E6A0204");

	UObject::ProcessEvent(Func, nullptr);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.ExecuteUbergraph_M_MED_Mystic_AnimBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UM_MED_Mystic_AnimBP_C::ExecuteUbergraph_M_MED_Mystic_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_M_MED_Mystic_AnimBP");

	Params::M_MED_Mystic_AnimBP_C_ExecuteUbergraph_M_MED_Mystic_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.OnBeginSkydiving
// (Event, Public, BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::OnBeginSkydiving()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnBeginSkydiving");

	UObject::ProcessEvent(Func, nullptr);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.OnEndSkydiving
// (Event, Public, BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::OnEndSkydiving()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnEndSkydiving");

	UObject::ProcessEvent(Func, nullptr);
}


// Function M_MED_Mystic_AnimBP.M_MED_Mystic_AnimBP_C.OnParachuteOpened
// (Event, Public, BlueprintEvent)

void UM_MED_Mystic_AnimBP_C::OnParachuteOpened()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnParachuteOpened");

	UObject::ProcessEvent(Func, nullptr);
}

}

