#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Male_Medium_Mystic_Head_AnimBP

#include "Basic.hpp"

#include "Fortnite_Base_Head_Export_Skeleton_AnimBP_structs.hpp"


namespace SDK
{

// ScriptStruct Male_Medium_Mystic_Head_AnimBP.Male_Medium_Mystic_Head_AnimBP_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0160 - 0x0160)
struct Male_Medium_Mystic_Head_AnimBP::FAnimBlueprintGeneratedConstantData final : public Fortnite_Base_Head_Export_Skeleton_AnimBP::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(Male_Medium_Mystic_Head_AnimBP::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on Male_Medium_Mystic_Head_AnimBP::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(Male_Medium_Mystic_Head_AnimBP::FAnimBlueprintGeneratedConstantData) == 0x000160, "Wrong size on Male_Medium_Mystic_Head_AnimBP::FAnimBlueprintGeneratedConstantData");

}

