#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VKEditGameplay

#include "Basic.hpp"

#include "VKEditGameplay_classes.hpp"
#include "VKEditGameplay_parameters.hpp"


namespace SDK
{

// Function VKEditGameplay.VKEditPlayspace.OnClientActivatedContent
// (Final, Native, Private, HasOutParams)
// Parameters:
// struct FUniqueNetIdRepl                 ClientNetId                                            (ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AVKEditPlayspace::OnClientActivatedContent(const struct FUniqueNetIdRepl& ClientNetId)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnClientActivatedContent");

	Params::VKEditPlayspace_OnClientActivatedContent Parms{};

	Parms.ClientNetId = std::move(ClientNetId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VKEditGameplay.PlayspaceComponent_EditConnectionManager.OnRep_EditConnections
// (Final, Native, Protected)

void UPlayspaceComponent_EditConnectionManager::OnRep_EditConnections()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnRep_EditConnections");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VKEditGameplay.PlayspaceComponent_HUDVisibilityComponent.OnRep_MatchHasStarted
// (Final, Native, Protected)

void UPlayspaceComponent_HUDVisibilityComponent::OnRep_MatchHasStarted()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnRep_MatchHasStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VKEditGameplay.PlayspaceComponent_HUDVisibilityComponent.OnRep_PlayersToHideUIFor
// (Final, Native, Protected)

void UPlayspaceComponent_HUDVisibilityComponent::OnRep_PlayersToHideUIFor()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnRep_PlayersToHideUIFor");

	UObject::ProcessEvent(Func, nullptr);
}

}

