#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace ButtonStyle_Empty_0 { class UButtonStyle_Empty_C; }

namespace BP_Shotgun_SG_BFPA { struct FAnimBlueprintGeneratedConstantData; }

namespace Mechanical_Engineer_Female_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Blueprint_Paper_VIM { struct FAnimBlueprintGeneratedConstantData; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace F_MED_Treasure_Hunter_Fashion_AnimBp { struct FAnimBlueprintGeneratedConstantData; }

namespace M_MED_Mystic_FaceAcc_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace SK_MachineGun_Clip_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MED_Ramirez_Fallback_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace Fortnite_Player_FullBody_LinkedGraph_Template { struct FAnimBlueprintGeneratedConstantData; }

namespace Fringe_Plank_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_AssaultRifle_FrontClip_SideAction { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MED_ASN_Sarah_Head_01_AnimBP_Child { struct FAnimBlueprintGeneratedConstantData; }

namespace Male_Medium_Mystic_Head_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_AssaultRifle_FrontClip_BackAction { struct FAnimBlueprintGeneratedConstantData; }

namespace ButtonStyle_Empty { class UButtonStyle_Empty_C; }


namespace Fortnite_Player_LowerBodyJog_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace HighTower_Tapas_Axe_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace SwimmingAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace MenuScreen_Athena
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Fortnite_Player_PostProcessProceduralFixUp_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_SkyDiveAndGlide_AnimBlueprint
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace M_MED_Mystic_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Fortnite_M_Avg_Player_ZipLine_AnimBlueprint
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_Player_DBNOCarried_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace M_MED_Mystic_Deform_CtrlRig_twists
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace SlidingLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_M_Avg_Player_Sprint_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace B_MasterPetAnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace M_MED_Mystic_Deform_CtrlRig_sculpters
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace Fortnite_M_Avg_Player_Goop_AnimBlueprint
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace B_AnimBP_HightowerRadish
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Fortnite_M_Avg_Player_DBNO_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace F_MED_ASN_Sarah_Head_01_Dyn_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Fortnite_M_Avg_Player_AnimBlueprint
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace F_MED_TreasureHunterFash_FaceAcc_AnimBp
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_Base_Head_Export_Skeleton_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Galileo_LobsterLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
