#pragma once

// Generated by Sarah's Offset Finder - https://github.com/plooshi/SkidFinder
// Fortnite version: 20.4
#include <stdint.h>
#include <array>
namespace SDK {
    class UNetDriver;
    class UObject;
    class UClass;
    class UField;
    class FField;
    class UEngine;
    class FName;
    struct FURL;
    class UReplicationDriver;
    class UWorld;
    class AOnlineBeaconHost;
};
namespace UC {
    class FString;
}
class FFrame;

namespace Jeremy {
    inline auto ImageBase = *(uint64_t*)(__readgsqword(0x60) + 0x10);
    namespace Offsets {
        inline uint64_t Step = 0xf6d050;
        inline uint64_t StepExplicitProperty = 0x10a04c0;
        inline uint64_t GetWorldContext = 0xf124b4;
        inline uint64_t CreateNetDriverWorldContext = 0x17b0ea0;
        inline uint64_t InitHost = 0x567d4a4;
        inline uint64_t PauseBeaconRequests = 0x6d00a04;
        inline uint64_t InitListen = 0x567d81c;
        inline uint64_t SetWorld = 0x17ada40;
        inline uint64_t GetNetMode = 0xf5d6f8;
        inline uint64_t TickFlush = 0xd56288;
        inline uint64_t GetMaxTickRate = 0xe1b0cc;
        inline uint64_t DispatchRequest = 0x16bbfe0;
        inline uint64_t Realloc = 0x1d6e680;
        inline uint64_t StaticFindObject = 0xf14d30;
        inline uint64_t StaticLoadObject = 0x1a34ba8;
        inline uint64_t GIsClient = 0xc425a74;
        inline uint64_t GIsServer = 0xc425a75;
        inline uint64_t GameSessionPatch = 0x1207905;
        inline uint64_t EncryptionPatch = 0x86230da;
        inline std::array<uint64_t, 4> NullFuncs = { 0x4834b50, 0x6d007f0 };
        inline std::array<uint64_t, 1> RetTrueFuncs = { 0x5225ae4 };

        //Replication Offsets

        inline uint64_t GetViewTarget = 0xF22364;
        inline uint64_t CallPreReplication = 0x82A7038;
        inline uint64_t RemoveNetworkActor = 0x1273970;
        inline uint64_t SendClientAdjustment = 0x83435F0;
        inline uint64_t CloseActorChannel = 0x8381470;
        inline uint64_t FindActorChannelRef = 0x83993A0;
        inline uint64_t StartBecomingDormant = 0x838F608;
        inline uint64_t CreateChannelByName = 0x16FDA6C;
        inline uint64_t SetChannelActor = 0x1273EC0;
        inline uint64_t ReplicateActor = 0x838C068;
        inline uint64_t SetChannelActorForDestroy = 0x838E794;
        inline uint64_t SupportsObject = 0xF31524;
        inline uint64_t GetArchetype = 0xF830D4;
        inline uint64_t IsNetReady = 0x8479048;
        inline uint64_t ClientHasInitializedLevelFor = 0x8473B58;
        inline uint64_t CloseConnection = 0x17AE720;
    };

    namespace Vfts {
    };

    namespace Funcs {
        inline auto Step = (void (*)(FFrame*, SDK::UObject*, void* const)) (ImageBase + Offsets::Step);
        inline auto StepExplicitProperty = (void (*)(FFrame*, void* const, SDK::FField*)) (ImageBase + Offsets::StepExplicitProperty);
        inline auto InitHost = (bool (*)(SDK::AOnlineBeaconHost*)) (ImageBase + Offsets::InitHost);
        inline auto PauseBeaconRequests = (void (*)(SDK::AOnlineBeaconHost*, bool)) (ImageBase + Offsets::PauseBeaconRequests);
        inline auto InitListen = (bool (*)(SDK::UNetDriver*, SDK::UWorld*, SDK::FURL&, bool, UC::FString&)) (ImageBase + Offsets::InitListen);
        inline auto SetWorld = (void (*)(SDK::UNetDriver*, SDK::UWorld*)) (ImageBase + Offsets::SetWorld);
        inline auto Realloc = (void* (*)(void*, __int64, unsigned int)) (ImageBase + Offsets::Realloc);
        inline auto StaticFindObject = (SDK::UObject * (*)(SDK::UClass*, SDK::UObject*, const wchar_t*, bool)) (ImageBase + Offsets::StaticFindObject);
        inline auto StaticLoadObject = (SDK::UObject * (*)(SDK::UClass*, SDK::UObject*, const wchar_t*, const wchar_t*, uint32_t, SDK::UObject*, bool)) (ImageBase + Offsets::StaticLoadObject);
    };
};